name = "PortfolioOptimization"
uuid = "62ad7d03-6272-4f3a-b233-5ac6bdd15ff6"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>", "Aline Nascimento Xavier <alinex59@gmail.com>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]